Allow the console to be opened at a directory
openflighthpc/flight-console-api pull request #7
Opened 2021-04-13 16:36 UTC by WilliamMcCumstie

A `dir` query parameter has been added to the `/ssh/host/:ip` to specify where the `console` should open:

* `GET /ssh/host/:ip?dir=/path/to/location`

---

As the `SSH2` library does not natively support "change directory", by running `cd` command within  the connection:

https://github.com/openflighthpc/flight-console-api/blob/30bd2b04fe851c6662b4d1119eba61ab0fc68de2/src/sshConnection.js#L128

NOTE: This is essentially equivalent to running the following whilst still respecting the user's shell:
`ssh <ip>  "cd <dir> ; bash --login"`

This means the output of the `cd` command is visible to the user. I tried a few different ways to prevent this but concluded its best just to leave it. The rejected strategies include:

* Turning off terminal `ECHO` (`stty -echo`) => Ignored by `tcsh`, ugly in bash
* Magic trailing comments (`cd <dir> #--remove-me--`) => Breaks `tcsh`
* Re-creating the shell after the `cd` => Double prints the welcome banner OR became overly complicated.

---

As the output of `cd` is visible, ideally it should not result in an error. To prevent missing directories emitting an ugly output, their existence is first checked using the `SFTP` protocol.

This proved to be easier than trying to determine the directories existence using `ls`.

2021-04-21 15:24 UTC, benarmston commented
@WilliamMcCumstie / @ColonelPanicks what are your thoughts on this:

Given the following directory structure:

```
$ find foo/
foo/
foo/bar
foo/bar;date
```

If I navigate to `?dir=foo/bar;date` I get the following interaction:

![image](https://user-images.githubusercontent.com/287050/115578636-601d8c80-a2bd-11eb-9cc8-72bea7d45eea.png)

Removing either `foo/bar` or `foo/bar;date` prevents the injection attack.  So if an attacker can create arbitrary directories on the server they can execute arbitrary commands on the server.

2021-04-22 16:09 UTC, WilliamMcCumstie commented
As discussed IRL, the injection has been prevented by adding a whitelist of the following characters: `/^[0-9a-zA-Z_ ./-]*$/`

2021-04-23 12:07 UTC, benarmston requested changes
The injection attack seems to have been fixed.  I've added another couple of comments below.

2021-04-23 15:47 UTC, WilliamMcCumstie commented on src/sshConnection.js
> +            conn.end();
https://github.com/openflighthpc/flight-console-api/pull/7/commits/23d50e463be86199688a8221072c790e9ccb3d30

2021-04-23 15:47 UTC, WilliamMcCumstie commented on src/sshConnection.js
> -      })
Rogue rebase:
https://github.com/openflighthpc/flight-console-api/pull/7/commits/23d50e463be86199688a8221072c790e9ccb3d30

2021-04-28 15:57 UTC, merged